### ISSUE TITLE
Demo url seems to be outdated

### ISSUE THREAD

**Issue by PatrickHuetter** [fhopf/akka-crawler-example#5]
Using runSequential i get the following exception:

```
2317 [main] ERROR de.fhopf.akka.Executor - org.htmlparser.util.ParserException: Exception getting input stream from http://www.synyx.de/unternehmen/jobs/systemintegration/ (http://www.synyx.de/unternehmen/jobs/systemintegration/).
java.lang.IllegalStateException: org.htmlparser.util.ParserException: Exception getting input stream from http://www.synyx.de/unternehmen/jobs/systemintegration/ (http://www.synyx.de/unternehmen/jobs/systemintegration/).
    at de.fhopf.akka.HtmlParserPageRetriever.fetchPageContent(HtmlParserPageRetriever.java:39)
    at de.fhopf.akka.sequential.SequentialExecution.downloadAndIndex(SequentialExecution.java:24)
    at de.fhopf.akka.Executor.execute(Executor.java:48)
    at de.fhopf.akka.sequential.SequentialExecution.main(SequentialExecution.java:36)
Caused by: org.htmlparser.util.ParserException: Exception getting input stream from http://www.synyx.de/unternehmen/jobs/systemintegration/ (http://www.synyx.de/unternehmen/jobs/systemintegration/).
    at org.htmlparser.lexer.Page.setConnection(Page.java:595)
    at org.htmlparser.lexer.Page.<init>(Page.java:134)
    at org.htmlparser.lexer.Lexer.<init>(Lexer.java:186)
    at org.htmlparser.Parser.setResource(Parser.java:398)
    at org.htmlparser.Parser.<init>(Parser.java:317)
    at org.htmlparser.Parser.<init>(Parser.java:331)
    at de.fhopf.akka.HtmlParserPageRetriever.fetchPageContent(HtmlParserPageRetriever.java:33)
    ... 3 more
```

Seems that the url isn't available anymore.

**Comment by fhopf** [comment]
Thanks for reporting this. Unfortunately I can't do anything about this (besides being more fault tolerant :) ): This url is crawled from one on the other pages, this seems to be a problem with the server. I'll let them know about the problem and hope they will fix it.
